import { QuestionsAdd,QuestionsType,QuestionsView,QuestionViewEdit,QuestionsDetail} from "../views/Home/Questins";
import { AddUser,UserShow } from "../views/Home/UserGuan";
import { AddExam ,ListExam,createNew,ExamDetail} from "../views/Home/Exam";
import {Awaiting,ExamStudent,PaperSExamDetail} from "../views/Home/papers";
import {Classroom,Grade,Student} from '../views/Home/ClassGrad'
export default {
    routes:[
        //试卷管理
        {
            name:"router.questions",
            children:[
                {
                    name:"router.questions.add",
                    id:"main-addQuestions",
                    path:"/questions/add",
                    component:QuestionsAdd
                },
                {
                    name:"router.questions.type",
                    id:"main-questionsType",
                    path:"/questions/type",
                    component:QuestionsType
                },{
                    name:"router.questions.view",
                    id:"main-questionsView",
                    path:"/questions/view",
                    component:QuestionsView
                },{
                    name:"",
                    id:"main-editQuestions",
                    path:"/questions/Edit",
                    component:QuestionViewEdit
                },{
                    name:"",
                    id:"main-questionsDetail",
                    path:"/questions/Detail",
                    component:QuestionsDetail
                }
            ]
        },
        //用户管理
        {
            name:"router.userGuan",
            children:[
                {
                    name:"router.userGuan.addUser",
                    id:"main-addUser",
                    path:"/userGuan/addUser",
                    component:AddUser
                },
                {
                    name:"router.userGuan.UserShow",
                    id:"main-showUser",
                    path:"/userGuan/UserShow",
                    component:UserShow
                }
            ]
        },
        //考试管理
        {
            name:"router.exam",
            children:[
                {
                    name:"router.exam.addexam",
                    id:"main-addExam",
                    path:"/exam/addexam",
                    component:AddExam
                },
                {
                    name:"router.exam.listExam",
                    id:"main-examList",
                    path:"/exam/listExam",
                    component:ListExam
                },
                {
                    name:"",
                    id:"main-examEdit",
                    path:"/exam/edit",
                    component:createNew
                },
                {
                    name:"",
                    id:"main-examDetail",
                    path:"/exam/Detail",
                    component:ExamDetail
                }
            ]
        },
        //班级管理
        {
            name:"router.classGrad",
            children:[
                {
                    name:"router.classGrad.grad",//班级管理
                    id:"main-grade",
                    path:"/home/grade",
                    component:Grade
                },
                {
                    name:"router.classGrad.Classroom",//教室管理
                    id:"main-room",
                    path:"/home/room",
                    component:Classroom
                },
                {
                    name:"router.classGrad.student",//学生管理
                    id:"main-student",
                    path:"/home/student",
                    component:Student
                }
            ]
        },
        //阅卷管理
        {
            name:"router.Marking",
            children:[
                {
                    name:"router.classGrad.grad",//待批班级
                    id:"main-examPaperClassmate",
                    path:"/papers/Awaiting",
                    component:Awaiting//ExamStudent
                },
                {
                    name:"",//获取学生试卷列表 
                    id:"main-examPaperClassList",
                    path:"/papers/ClassList",
                    component:ExamStudent
                },
                {
                    name:"",//阅卷
                    id:"main-examinationPapers",
                    path:"/papers/detail",
                    component:PaperSExamDetail
                }
            ]
        }
    ]
}